---

version: "3.3"

services:
  gradle:
    image: "gradle:7.2.0-jdk17"
    working_dir: /d/Groovy/epam-groovy-lab-tasks
    stdin_open: true
    tty: true
    entrypoint: "/bin/bash"
    volumes:
      - .:/d/Groovy/epam-groovy-lab-tasks